### ISSUE TITLE
Could Not Be Compiled

### ISSUE THREAD

**Issue by RAPrograms** [JonasMolgaard/UBIKSolver#8]
I am relatively new to making games in unreal, so when I encountered this error on UR 5 I thought it was just because its a preview thing and tried it on UR 4.27.2 same thing and I have no clue how to fix this

![E1](https://user-images.githubusercontent.com/56273305/158814702-aef6cf38-9028-41b5-a276-58611a51c480.PNG)

after pressing yes

![E2](https://user-images.githubusercontent.com/56273305/158814744-4d5844e4-a549-4ef6-8983-aec42426ad6f.PNG)

**Comment by Pterodactylw** [comment]
I have the Same issue

**Comment by GitGrove** [comment]
Had the same issue. Found clues on YouTube of all places... 

1. Install [Visual Studio 2019 ](https://learn.microsoft.com/en-us/visualstudio/releases/2019/release-notes)or later (I used 2019 Community Edition). 
2. During VS 2019 install you need to install some very specific packages, follow [these instructions from the Unreal Engine documentation](https://docs.unrealengine.com/5.1/en-US/setting-up-visual-studio-development-environment-for-cplusplus-projects-in-unreal-engine/) (link is for 5.1)
3. Open your project and you should be able to rebuild now. Wait patiently after clicking "rebuild". Unreal may seem unresponsive but it's doing its thing.

**Comment by niv-e** [comment]
same for me,
I tried to build it manually and I got the following error.
Does someone have any idea how to solve this issue?

`
warning C4996: 'USkinnedMeshComponent::SkeletalMesh': Replaced by SkinnedAsset. Use GetSkinnedAsset()/SetSkinnedAsset() instead, or GetSkeletalMeshAsset/SetSkeletalMeshAsset() when called from a USkeletalMeshComponent. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile
`

**Comment by kjduling** [comment]
@niv-e https://github.com/JonasMolgaard/UBIKSolver/pull/18

**Comment by JonasMolgaard** [comment]
kjduling made some recent changes that should fix it for compiling in 5.3. Closing this issue.
